---
name: PR Validation

on:
  pull_request:
    paths:
      - 'cmd/**'
      - 'pkg/**'
      - 'internal/**'
      - 'go.mod'
      - 'go.sum'
      - 'test/**'
      - '.github/workflows/**'
    branches:
      - main
jobs:
  build:
    runs-on: [self-hosted, csg, dt-csg-runtime]
    strategy:
      matrix:
        go-version: ['1.22.x']

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          cache-dependency-path: subdir/go.sum
      - name: Display Go version
        run: |
            go version
            go get .
      - name: Compile
        run: make compile
      - name: Run Test
        run: go test -race test/...