---
name: YAML Lint

on:
  push:
    paths:
      - '.github/workflows/**.yaml'
      - '.github/workflows/**.yml'
      - 'src/**.yaml'
      - 'cmd/**.yaml'
      - 'pkg/**.yaml'
      - '!docs/**'

jobs:
  golangci:
    name: YAML Lint
    runs-on: [self-hosted, macOS, X64]
    steps:
      - uses: actions/checkout@v3
      - name: yaml-lint
        uses: ibiqlik/action-yamllint@v3
        with:
          config_file: .yamllint.yaml